import type { User, Project, Task, Comment } from './types'

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Carlos Rodríguez',
    email: 'carlos.rodriguez@fesc.edu.co',
    role: 'administrador',
  },
  {
    id: '2',
    name: 'María García',
    email: 'maria.garcia@fesc.edu.co',
    role: 'lider',
  },
  {
    id: '3',
    name: 'Juan Pérez',
    email: 'juan.perez@fesc.edu.co',
    role: 'desarrollador',
  },
  {
    id: '4',
    name: 'Ana Martínez',
    email: 'ana.martinez@fesc.edu.co',
    role: 'desarrollador',
  },
]

export const mockComments: Comment[] = [
  {
    id: 'c1',
    taskId: 't1',
    author: mockUsers[2],
    content: 'He iniciado el desarrollo del módulo de autenticación.',
    createdAt: new Date('2026-01-15T10:30:00'),
  },
  {
    id: 'c2',
    taskId: 't1',
    author: mockUsers[1],
    content: 'Excelente avance, Juan. Recuerda implementar validación de tokens.',
    createdAt: new Date('2026-01-15T14:00:00'),
  },
  {
    id: 'c3',
    taskId: 't2',
    author: mockUsers[3],
    content: 'El diseño del dashboard está listo para revisión.',
    createdAt: new Date('2026-01-16T09:00:00'),
  },
]

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Implementar autenticación de usuarios',
    description: 'Desarrollar el sistema de login con validación de credenciales y manejo de sesiones.',
    status: 'en-progreso',
    priority: 'alta',
    assignee: mockUsers[2],
    projectId: 'p1',
    comments: mockComments.filter(c => c.taskId === 't1'),
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 't2',
    title: 'Diseñar interfaz del dashboard',
    description: 'Crear el diseño visual del panel principal siguiendo la identidad FESC.',
    status: 'hecha',
    priority: 'alta',
    assignee: mockUsers[3],
    projectId: 'p1',
    comments: mockComments.filter(c => c.taskId === 't2'),
    createdAt: new Date('2026-01-08'),
    updatedAt: new Date('2026-01-16'),
  },
  {
    id: 't3',
    title: 'Configurar base de datos',
    description: 'Establecer la estructura de tablas y relaciones para el sistema.',
    status: 'pendiente',
    priority: 'media',
    assignee: mockUsers[2],
    projectId: 'p1',
    comments: [],
    createdAt: new Date('2026-01-12'),
    updatedAt: new Date('2026-01-12'),
  },
  {
    id: 't4',
    title: 'Crear módulo de reportes',
    description: 'Implementar generación de reportes en PDF con estadísticas del proyecto.',
    status: 'pendiente',
    priority: 'baja',
    assignee: undefined,
    projectId: 'p1',
    comments: [],
    createdAt: new Date('2026-01-14'),
    updatedAt: new Date('2026-01-14'),
  },
  {
    id: 't5',
    title: 'Investigar frameworks de frontend',
    description: 'Evaluar opciones tecnológicas para el desarrollo del frontend.',
    status: 'hecha',
    priority: 'media',
    assignee: mockUsers[3],
    projectId: 'p2',
    comments: [],
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 't6',
    title: 'Definir arquitectura del sistema',
    description: 'Documentar la arquitectura técnica y patrones de diseño a utilizar.',
    status: 'en-progreso',
    priority: 'alta',
    assignee: mockUsers[1],
    projectId: 'p2',
    comments: [],
    createdAt: new Date('2026-01-06'),
    updatedAt: new Date('2026-01-17'),
  },
  {
    id: 't7',
    title: 'Preparar presentación final',
    description: 'Crear slides y demo para la presentación del proyecto.',
    status: 'pendiente',
    priority: 'media',
    assignee: undefined,
    projectId: 'p2',
    comments: [],
    createdAt: new Date('2026-01-18'),
    updatedAt: new Date('2026-01-18'),
  },
]

export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'Sistema de Gestión Académica',
    description: 'Plataforma integral para la administración de procesos académicos de la FESC, incluyendo inscripciones, calificaciones y seguimiento estudiantil.',
    leader: mockUsers[1],
    members: [mockUsers[1], mockUsers[2], mockUsers[3]],
    tasks: mockTasks.filter(t => t.projectId === 'p1'),
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'p2',
    name: 'App Móvil Estudiantil',
    description: 'Aplicación móvil para que los estudiantes accedan a sus horarios, calificaciones y notificaciones institucionales.',
    leader: mockUsers[1],
    members: [mockUsers[1], mockUsers[3]],
    tasks: mockTasks.filter(t => t.projectId === 'p2'),
    createdAt: new Date('2026-01-05'),
  },
]
